name: auto-merge

on:
  pull_request_target:
    types: [labeled]

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
