name: auto-merge

on:
  pull_request_target:
    types: [labeled]

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
